export const ordersData = [
  {
    id: 'MS100',
    customerName: 'John Doe',
    customerSource: 'Website',
    status: 'Closed',
    orderCost: '$150.00',
    createdAt: new Date('2022-01-15'),
  },
  {
    id: 'MS101',
    customerName: 'Jane Smith',
    customerSource: 'Mobile App',
    status: 'Pending',
    orderCost: '$200.50',
    createdAt: new Date('2022-01-16'),
  },
  {
    id: 'MS102',
    customerName: 'Michael Johnson',
    customerSource: 'Email Campaign',
    status: 'Active',
    orderCost: '$300.00',
    createdAt: new Date('2022-01-17'),
  },
  {
    id: 'MS103',
    customerName: 'Emily Davis',
    customerSource: 'Referral',
    status: 'Closed',
    orderCost: '$125.75',
    createdAt: new Date('2022-01-18'),
  },
  {
    id: 'MS104',
    customerName: 'Christopher Wilson',
    customerSource: 'Social Media',
    status: 'Pending',
    orderCost: '$450.00',
    createdAt: new Date('2022-01-19'),
  },
  {
    id: 'MS105',
    customerName: 'Sarah Brown',
    customerSource: 'Affiliate Link',
    status: 'Active',
    orderCost: '$99.99',
    createdAt: new Date('2022-01-20'),
  },
  {
    id: 'MS106',
    customerName: 'David Garcia',
    customerSource: 'Website',
    status: 'Pending',
    orderCost: '$250.00',
    createdAt: new Date('2022-01-21'),
  },
  {
    id: 'MS107',
    customerName: 'Laura Martinez',
    customerSource: 'Mobile App',
    status: 'Closed',
    orderCost: '$350.20',
    createdAt: new Date('2022-01-22'),
  },
  {
    id: 'MS108',
    customerName: 'James Rodriguez',
    customerSource: 'Email Campaign',
    status: 'Active',
    orderCost: '$75.00',
    createdAt: new Date('2022-01-23'),
  },
  {
    id: 'MS109',
    customerName: 'Patricia Lee',
    customerSource: 'Referral',
    status: 'Pending',
    orderCost: '$120.50',
    createdAt: new Date('2022-01-24'),
  },
  {
    id: 'MS110',
    customerName: 'Robert Wilson',
    customerSource: 'Social Media',
    status: 'Active',
    orderCost: '$180.75',
    createdAt: new Date('2022-01-25'),
  },
  {
    id: 'MS111',
    customerName: 'Linda Clark',
    customerSource: 'Affiliate Link',
    status: 'Closed',
    orderCost: '$290.00',
    createdAt: new Date('2022-01-26'),
  },
  {
    id: 'MS112',
    customerName: 'Daniel Harris',
    customerSource: 'Website',
    status: 'Pending',
    orderCost: '$410.10',
    createdAt: new Date('2022-01-27'),
  },
  {
    id: 'MS113',
    customerName: 'Barbara Lewis',
    customerSource: 'Mobile App',
    status: 'Active',
    orderCost: '$350.00',
    createdAt: new Date('2022-01-28'),
  },
  {
    id: 'MS114',
    customerName: 'Matthew Walker',
    customerSource: 'Email Campaign',
    status: 'Closed',
    orderCost: '$60.00',
    createdAt: new Date('2022-01-29'),
  },
  {
    id: 'MS115',
    customerName: 'Jennifer Hall',
    customerSource: 'Referral',
    status: 'Pending',
    orderCost: '$500.00',
    createdAt: new Date('2022-01-30'),
  },
  {
    id: 'MS116',
    customerName: 'Charles Young',
    customerSource: 'Website',
    status: 'Active',
    orderCost: '$225.00',
    createdAt: new Date('2022-02-01'),
  },
  {
    id: 'MS117',
    customerName: 'Susan King',
    customerSource: 'Social Media',
    status: 'Closed',
    orderCost: '$135.50',
    createdAt: new Date('2022-02-02'),
  },
  {
    id: 'MS118',
    customerName: 'Thomas Wright',
    customerSource: 'Email Campaign',
    status: 'Pending',
    orderCost: '$275.20',
    createdAt: new Date('2022-02-03'),
  },
  {
    id: 'MS119',
    customerName: 'Karen Scott',
    customerSource: 'Referral',
    status: 'Active',
    orderCost: '$99.99',
    createdAt: new Date('2022-02-04'),
  },
  {
    id: 'MS120',
    customerName: 'Nancy Green',
    customerSource: 'Affiliate Link',
    status: 'Closed',
    orderCost: '$420.00',
    createdAt: new Date('2022-02-05'),
  },
  {
    id: 'MS121',
    customerName: 'Paul Adams',
    customerSource: 'Mobile App',
    status: 'Pending',
    orderCost: '$310.75',
    createdAt: new Date('2022-02-06'),
  },
  {
    id: 'MS122',
    customerName: 'Patricia Baker',
    customerSource: 'Website',
    status: 'Active',
    orderCost: '$180.00',
    createdAt: new Date('2022-02-07'),
  },
  {
    id: 'MS123',
    customerName: 'Donald Gonzalez',
    customerSource: 'Social Media',
    status: 'Pending',
    orderCost: '$299.50',
    createdAt: new Date('2022-02-08'),
  },
  {
    id: 'MS124',
    customerName: 'Emily Nelson',
    customerSource: 'Email Campaign',
    status: 'Active',
    orderCost: '$145.30',
    createdAt: new Date('2022-02-09'),
  },
  {
    id: 'MS125',
    customerName: 'Matthew Carter',
    customerSource: 'Referral',
    status: 'Closed',
    orderCost: '$75.00',
    createdAt: new Date('2022-02-10'),
  },
  {
    id: 'MS126',
    customerName: 'Linda Mitchell',
    customerSource: 'Affiliate Link',
    status: 'Pending',
    orderCost: '$540.99',
    createdAt: new Date('2022-02-11'),
  },
  {
    id: 'MS127',
    customerName: 'James Perez',
    customerSource: 'Website',
    status: 'Active',
    orderCost: '$365.40',
    createdAt: new Date('2022-02-12'),
  },
  {
    id: 'MS128',
    customerName: 'Barbara Roberts',
    customerSource: 'Mobile App',
    status: 'Closed',
    orderCost: '$125.50',
    createdAt: new Date('2022-02-13'),
  },
  {
    id: 'MS129',
    customerName: 'Jessica Turner',
    customerSource: 'Email Campaign',
    status: 'Pending',
    orderCost: '$65.00',
    createdAt: new Date('2022-02-14'),
  },
  {
    id: 'MS130',
    customerName: 'Michael Phillips',
    customerSource: 'Referral',
    status: 'Active',
    orderCost: '$390.00',
    createdAt: new Date('2022-02-15'),
  },
  {
    id: 'MS131',
    customerName: 'Kevin Campbell',
    customerSource: 'Affiliate Link',
    status: 'Closed',
    orderCost: '$420.00',
    createdAt: new Date('2022-02-16'),
  },
  {
    id: 'MS132',
    customerName: 'Laura White',
    customerSource: 'Website',
    status: 'Pending',
    orderCost: '$310.00',
    createdAt: new Date('2022-02-17'),
  },
  {
    id: 'MS133',
    customerName: 'Brian Harris',
    customerSource: 'Social Media',
    status: 'Active',
    orderCost: '$280.50',
    createdAt: new Date('2022-02-18'),
  },
  {
    id: 'MS134',
    customerName: 'Sophia Martinez',
    customerSource: 'Email Campaign',
    status: 'Closed',
    orderCost: '$175.00',
    createdAt: new Date('2022-02-19'),
  },
  {
    id: 'MS135',
    customerName: 'Samuel Johnson',
    customerSource: 'Referral',
    status: 'Pending',
    orderCost: '$220.20',
    createdAt: new Date('2022-02-20'),
  },
  {
    id: 'MS136',
    customerName: 'Emma Wilson',
    customerSource: 'Affiliate Link',
    status: 'Active',
    orderCost: '$480.00',
    createdAt: new Date('2022-02-21'),
  },
  {
    id: 'MS001',
    customerName: 'Alice Anderson',
    customerSource: 'Website',
    status: 'Active',
    orderCost: '$120.00',
    createdAt: new Date('2024-10-01'),
  },
  {
    id: 'MS002',
    customerName: 'Bob Brown',
    customerSource: 'Mobile App',
    status: 'Pending',
    orderCost: '$200.00',
    createdAt: new Date('2024-10-02'),
  },
  {
    id: 'MS003',
    customerName: 'Charlie Clark',
    customerSource: 'Email Campaign',
    status: 'Closed',
    orderCost: '$150.00',
    createdAt: new Date('2024-10-03'),
  },
  {
    id: 'MS004',
    customerName: 'Diana Davis',
    customerSource: 'Referral',
    status: 'Active',
    orderCost: '$300.50',
    createdAt: new Date('2024-10-04'),
  },
  {
    id: 'MS005',
    customerName: 'Evan Edwards',
    customerSource: 'Social Media',
    status: 'Pending',
    orderCost: '$250.75',
    createdAt: new Date('2024-10-05'),
  },
  {
    id: 'MS006',
    customerName: 'Fiona Garcia',
    customerSource: 'Affiliate Link',
    status: 'Closed',
    orderCost: '$80.25',
    createdAt: new Date('2024-10-06'),
  },
  {
    id: 'MS007',
    customerName: 'George Harris',
    customerSource: 'Website',
    status: 'Active',
    orderCost: '$130.99',
    createdAt: new Date('2024-10-07'),
  },
  {
    id: 'MS008',
    customerName: 'Hannah Johnson',
    customerSource: 'Mobile App',
    status: 'Pending',
    orderCost: '$190.00',
    createdAt: new Date('2024-10-08'),
  },
  {
    id: 'MS009',
    customerName: 'Ian King',
    customerSource: 'Email Campaign',
    status: 'Closed',
    orderCost: '$220.50',
    createdAt: new Date('2024-10-09'),
  },
  {
    id: 'MS010',
    customerName: 'Julia Lee',
    customerSource: 'Referral',
    status: 'Active',
    orderCost: '$60.00',
    createdAt: new Date('2024-10-10'),
  },
  {
    id: 'MS011',
    customerName: 'Kyle Martinez',
    customerSource: 'Social Media',
    status: 'Pending',
    orderCost: '$400.00',
    createdAt: new Date('2024-10-11'),
  },
  {
    id: 'MS012',
    customerName: 'Laura Nelson',
    customerSource: 'Affiliate Link',
    status: 'Closed',
    orderCost: '$99.99',
    createdAt: new Date('2024-10-12'),
  },
  {
    id: 'MS013',
    customerName: 'Mark OBrien',
    customerSource: 'Website',
    status: 'Active',
    orderCost: '$175.00',
    createdAt: new Date('2024-10-13'),
  },
  {
    id: 'MS014',
    customerName: 'Nina Patel',
    customerSource: 'Mobile App',
    status: 'Pending',
    orderCost: '$300.25',
    createdAt: new Date('2024-10-14'),
  },
  {
    id: 'MS015',
    customerName: 'Oliver Quinn',
    customerSource: 'Email Campaign',
    status: 'Closed',
    orderCost: '$140.75',
    createdAt: new Date('2024-10-15'),
  },
  {
    id: 'MS016',
    customerName: 'Paula Roberts',
    customerSource: 'Referral',
    status: 'Active',
    orderCost: '$80.50',
    createdAt: new Date('2024-10-16'),
  },
  {
    id: 'MS017',
    customerName: 'Quentin Smith',
    customerSource: 'Social Media',
    status: 'Pending',
    orderCost: '$210.30',
    createdAt: new Date('2024-10-17'),
  },
  {
    id: 'MS018',
    customerName: 'Rachel Taylor',
    customerSource: 'Affiliate Link',
    status: 'Closed',
    orderCost: '$99.00',
    createdAt: new Date('2024-10-18'),
  },
  {
    id: 'MS019',
    customerName: 'Steve Underwood',
    customerSource: 'Website',
    status: 'Active',
    orderCost: '$150.00',
    createdAt: new Date('2024-10-19'),
  },
  {
    id: 'MS020',
    customerName: 'Tina Vance',
    customerSource: 'Mobile App',
    status: 'Pending',
    orderCost: '$340.20',
    createdAt: new Date('2024-10-20'),
  },
  {
    id: 'MS021',
    customerName: 'Uma Washington',
    customerSource: 'Email Campaign',
    status: 'Closed',
    orderCost: '$225.00',
    createdAt: new Date('2024-10-21'),
  },
  {
    id: 'MS022',
    customerName: 'Victor Xu',
    customerSource: 'Referral',
    status: 'Active',
    orderCost: '$270.50',
    createdAt: new Date('2024-10-22'),
  },
  {
    id: 'MS023',
    customerName: 'Wendy Young',
    customerSource: 'Social Media',
    status: 'Pending',
    orderCost: '$150.00',
    createdAt: new Date('2024-10-23'),
  },
  {
    id: 'MS024',
    customerName: 'Xander Zane',
    customerSource: 'Affiliate Link',
    status: 'Closed',
    orderCost: '$95.25',
    createdAt: new Date('2024-10-24'),
  },
  {
    id: 'MS025',
    customerName: 'Yara Allen',
    customerSource: 'Website',
    status: 'Active',
    orderCost: '$280.00',
    createdAt: new Date('2024-10-25'),
  },
  {
    id: 'MS026',
    customerName: 'Zoe Bell',
    customerSource: 'Mobile App',
    status: 'Pending',
    orderCost: '$190.50',
    createdAt: new Date('2024-10-26'),
  },
  {
    id: 'MS027',
    customerName: 'Aaron Cook',
    customerSource: 'Email Campaign',
    status: 'Closed',
    orderCost: '$220.00',
    createdAt: new Date('2024-10-27'),
  },
  {
    id: 'MS028',
    customerName: 'Bella Drew',
    customerSource: 'Referral',
    status: 'Active',
    orderCost: '$130.00',
    createdAt: new Date('2024-10-28'),
  },
  {
    id: 'MS029',
    customerName: 'Cody Frank',
    customerSource: 'Social Media',
    status: 'Pending',
    orderCost: '$250.00',
    createdAt: new Date('2024-10-29'),
  },
  {
    id: 'MS030',
    customerName: 'Daisy Gray',
    customerSource: 'Affiliate Link',
    status: 'Closed',
    orderCost: '$140.00',
    createdAt: new Date('2024-10-30'),
  },
  {
    id: 'MS100',
    customerName: 'John Doe',
    customerSource: 'Website',
    status: 'Closed',
    orderCost: '$150.00',
    createdAt: new Date('2022-01-15'),
  },
  {
    id: 'MS101',
    customerName: 'Jane Smith',
    customerSource: 'Mobile App',
    status: 'Pending',
    orderCost: '$200.50',
    createdAt: new Date('2022-01-16'),
  },
  {
    id: 'MS102',
    customerName: 'Michael Johnson',
    customerSource: 'Email Campaign',
    status: 'Active',
    orderCost: '$300.00',
    createdAt: new Date('2022-01-17'),
  },
  {
    id: 'MS103',
    customerName: 'Emily Davis',
    customerSource: 'Referral',
    status: 'Closed',
    orderCost: '$125.75',
    createdAt: new Date('2022-01-18'),
  },
  {
    id: 'MS104',
    customerName: 'Christopher Wilson',
    customerSource: 'Social Media',
    status: 'Pending',
    orderCost: '$450.00',
    createdAt: new Date('2022-01-19'),
  },
  {
    id: 'MS105',
    customerName: 'Sarah Brown',
    customerSource: 'Affiliate Link',
    status: 'Active',
    orderCost: '$99.99',
    createdAt: new Date('2022-01-20'),
  },
  {
    id: 'MS106',
    customerName: 'David Garcia',
    customerSource: 'Website',
    status: 'Pending',
    orderCost: '$250.00',
    createdAt: new Date('2022-01-21'),
  },
  {
    id: 'MS107',
    customerName: 'Laura Martinez',
    customerSource: 'Mobile App',
    status: 'Closed',
    orderCost: '$350.20',
    createdAt: new Date('2022-01-22'),
  },
  {
    id: 'MS108',
    customerName: 'James Rodriguez',
    customerSource: 'Email Campaign',
    status: 'Active',
    orderCost: '$75.00',
    createdAt: new Date('2022-01-23'),
  },
  {
    id: 'MS109',
    customerName: 'Patricia Lee',
    customerSource: 'Referral',
    status: 'Pending',
    orderCost: '$120.50',
    createdAt: new Date('2022-01-24'),
  },
  {
    id: 'MS110',
    customerName: 'Robert Wilson',
    customerSource: 'Social Media',
    status: 'Active',
    orderCost: '$180.75',
    createdAt: new Date('2022-01-25'),
  },
  {
    id: 'MS111',
    customerName: 'Linda Clark',
    customerSource: 'Affiliate Link',
    status: 'Closed',
    orderCost: '$290.00',
    createdAt: new Date('2022-01-26'),
  },
  {
    id: 'MS112',
    customerName: 'Daniel Harris',
    customerSource: 'Website',
    status: 'Pending',
    orderCost: '$410.10',
    createdAt: new Date('2022-01-27'),
  },
  {
    id: 'MS113',
    customerName: 'Barbara Lewis',
    customerSource: 'Mobile App',
    status: 'Active',
    orderCost: '$350.00',
    createdAt: new Date('2022-01-28'),
  },
  {
    id: 'MS114',
    customerName: 'Matthew Walker',
    customerSource: 'Email Campaign',
    status: 'Closed',
    orderCost: '$60.00',
    createdAt: new Date('2022-01-29'),
  },
  {
    id: 'MS115',
    customerName: 'Jennifer Hall',
    customerSource: 'Referral',
    status: 'Pending',
    orderCost: '$500.00',
    createdAt: new Date('2022-01-30'),
  },
  {
    id: 'MS116',
    customerName: 'Charles Young',
    customerSource: 'Website',
    status: 'Active',
    orderCost: '$225.00',
    createdAt: new Date('2022-02-01'),
  },
  {
    id: 'MS117',
    customerName: 'Susan King',
    customerSource: 'Social Media',
    status: 'Closed',
    orderCost: '$135.50',
    createdAt: new Date('2022-02-02'),
  },
  {
    id: 'MS118',
    customerName: 'Thomas Wright',
    customerSource: 'Email Campaign',
    status: 'Pending',
    orderCost: '$275.20',
    createdAt: new Date('2022-02-03'),
  },
  {
    id: 'MS119',
    customerName: 'Karen Scott',
    customerSource: 'Referral',
    status: 'Active',
    orderCost: '$99.99',
    createdAt: new Date('2022-02-04'),
  },
  {
    id: 'MS120',
    customerName: 'Nancy Green',
    customerSource: 'Affiliate Link',
    status: 'Closed',
    orderCost: '$420.00',
    createdAt: new Date('2022-02-05'),
  },
  {
    id: 'MS121',
    customerName: 'Paul Adams',
    customerSource: 'Mobile App',
    status: 'Pending',
    orderCost: '$310.75',
    createdAt: new Date('2022-02-06'),
  },
  {
    id: 'MS122',
    customerName: 'Patricia Baker',
    customerSource: 'Website',
    status: 'Active',
    orderCost: '$180.00',
    createdAt: new Date('2022-02-07'),
  },
  {
    id: 'MS123',
    customerName: 'Donald Gonzalez',
    customerSource: 'Social Media',
    status: 'Pending',
    orderCost: '$299.50',
    createdAt: new Date('2022-02-08'),
  },
  {
    id: 'MS124',
    customerName: 'Emily Nelson',
    customerSource: 'Email Campaign',
    status: 'Active',
    orderCost: '$145.30',
    createdAt: new Date('2022-02-09'),
  },
  {
    id: 'MS125',
    customerName: 'Matthew Carter',
    customerSource: 'Referral',
    status: 'Closed',
    orderCost: '$75.00',
    createdAt: new Date('2022-02-10'),
  },
  {
    id: 'MS126',
    customerName: 'Linda Mitchell',
    customerSource: 'Affiliate Link',
    status: 'Pending',
    orderCost: '$540.99',
    createdAt: new Date('2022-02-11'),
  },
  {
    id: 'MS127',
    customerName: 'James Perez',
    customerSource: 'Website',
    status: 'Active',
    orderCost: '$365.40',
    createdAt: new Date('2022-02-12'),
  },
  {
    id: 'MS128',
    customerName: 'Barbara Roberts',
    customerSource: 'Mobile App',
    status: 'Closed',
    orderCost: '$125.50',
    createdAt: new Date('2022-02-13'),
  },
  {
    id: 'MS129',
    customerName: 'Jessica Turner',
    customerSource: 'Email Campaign',
    status: 'Pending',
    orderCost: '$65.00',
    createdAt: new Date('2022-02-14'),
  },
  {
    id: 'MS130',
    customerName: 'Michael Phillips',
    customerSource: 'Referral',
    status: 'Active',
    orderCost: '$390.00',
    createdAt: new Date('2022-02-15'),
  },
  {
    id: 'MS131',
    customerName: 'Kevin Campbell',
    customerSource: 'Affiliate Link',
    status: 'Closed',
    orderCost: '$420.00',
    createdAt: new Date('2022-02-16'),
  },
  {
    id: 'MS132',
    customerName: 'Laura White',
    customerSource: 'Website',
    status: 'Pending',
    orderCost: '$310.00',
    createdAt: new Date('2022-02-17'),
  },
  {
    id: 'MS133',
    customerName: 'Brian Harris',
    customerSource: 'Social Media',
    status: 'Active',
    orderCost: '$280.50',
    createdAt: new Date('2022-02-18'),
  },
  {
    id: 'MS134',
    customerName: 'Sophia Martinez',
    customerSource: 'Email Campaign',
    status: 'Closed',
    orderCost: '$175.00',
    createdAt: new Date('2022-02-19'),
  },
  {
    id: 'MS135',
    customerName: 'Samuel Johnson',
    customerSource: 'Referral',
    status: 'Pending',
    orderCost: '$220.20',
    createdAt: new Date('2022-02-20'),
  },
  {
    id: 'MS136',
    customerName: 'Emma Wilson',
    customerSource: 'Affiliate Link',
    status: 'Active',
    orderCost: '$480.00',
    createdAt: new Date('2022-02-21'),
  },
  {
    id: 'MS001',
    customerName: 'Alice Anderson',
    customerSource: 'Website',
    status: 'Active',
    orderCost: '$120.00',
    createdAt: new Date('2024-10-01'),
  },
  {
    id: 'MS002',
    customerName: 'Bob Brown',
    customerSource: 'Mobile App',
    status: 'Pending',
    orderCost: '$200.00',
    createdAt: new Date('2024-10-02'),
  },
  {
    id: 'MS003',
    customerName: 'Charlie Clark',
    customerSource: 'Email Campaign',
    status: 'Closed',
    orderCost: '$150.00',
    createdAt: new Date('2024-10-03'),
  },
  {
    id: 'MS004',
    customerName: 'Diana Davis',
    customerSource: 'Referral',
    status: 'Active',
    orderCost: '$300.50',
    createdAt: new Date('2024-10-04'),
  },
  {
    id: 'MS005',
    customerName: 'Evan Edwards',
    customerSource: 'Social Media',
    status: 'Pending',
    orderCost: '$250.75',
    createdAt: new Date('2024-10-05'),
  },
  {
    id: 'MS006',
    customerName: 'Fiona Garcia',
    customerSource: 'Affiliate Link',
    status: 'Closed',
    orderCost: '$80.25',
    createdAt: new Date('2024-10-06'),
  },
  {
    id: 'MS007',
    customerName: 'George Harris',
    customerSource: 'Website',
    status: 'Active',
    orderCost: '$130.99',
    createdAt: new Date('2024-10-07'),
  },
  {
    id: 'MS008',
    customerName: 'Hannah Johnson',
    customerSource: 'Mobile App',
    status: 'Pending',
    orderCost: '$190.00',
    createdAt: new Date('2024-10-08'),
  },
  {
    id: 'MS009',
    customerName: 'Ian King',
    customerSource: 'Email Campaign',
    status: 'Closed',
    orderCost: '$220.50',
    createdAt: new Date('2024-10-09'),
  },
  {
    id: 'MS010',
    customerName: 'Julia Lee',
    customerSource: 'Referral',
    status: 'Active',
    orderCost: '$60.00',
    createdAt: new Date('2024-10-10'),
  },
  {
    id: 'MS011',
    customerName: 'Kyle Martinez',
    customerSource: 'Social Media',
    status: 'Pending',
    orderCost: '$400.00',
    createdAt: new Date('2024-10-11'),
  },
  {
    id: 'MS012',
    customerName: 'Laura Nelson',
    customerSource: 'Affiliate Link',
    status: 'Closed',
    orderCost: '$99.99',
    createdAt: new Date('2024-10-12'),
  },
  {
    id: 'MS013',
    customerName: 'Mark OBrien',
    customerSource: 'Website',
    status: 'Active',
    orderCost: '$175.00',
    createdAt: new Date('2024-10-13'),
  },
  {
    id: 'MS014',
    customerName: 'Nina Patel',
    customerSource: 'Mobile App',
    status: 'Pending',
    orderCost: '$300.25',
    createdAt: new Date('2024-10-14'),
  },
  {
    id: 'MS015',
    customerName: 'Oliver Quinn',
    customerSource: 'Email Campaign',
    status: 'Closed',
    orderCost: '$140.75',
    createdAt: new Date('2024-10-15'),
  },
  {
    id: 'MS016',
    customerName: 'Paula Roberts',
    customerSource: 'Referral',
    status: 'Active',
    orderCost: '$80.50',
    createdAt: new Date('2024-10-16'),
  },
  {
    id: 'MS017',
    customerName: 'Quentin Smith',
    customerSource: 'Social Media',
    status: 'Pending',
    orderCost: '$210.30',
    createdAt: new Date('2024-10-17'),
  },
  {
    id: 'MS018',
    customerName: 'Rachel Taylor',
    customerSource: 'Affiliate Link',
    status: 'Closed',
    orderCost: '$99.00',
    createdAt: new Date('2024-10-18'),
  },
  {
    id: 'MS019',
    customerName: 'Steve Underwood',
    customerSource: 'Website',
    status: 'Active',
    orderCost: '$150.00',
    createdAt: new Date('2024-10-19'),
  },
  {
    id: 'MS020',
    customerName: 'Tina Vance',
    customerSource: 'Mobile App',
    status: 'Pending',
    orderCost: '$340.20',
    createdAt: new Date('2024-10-20'),
  },
  {
    id: 'MS021',
    customerName: 'Uma Washington',
    customerSource: 'Email Campaign',
    status: 'Closed',
    orderCost: '$225.00',
    createdAt: new Date('2024-10-21'),
  },
  {
    id: 'MS022',
    customerName: 'Victor Xu',
    customerSource: 'Referral',
    status: 'Active',
    orderCost: '$270.50',
    createdAt: new Date('2024-10-22'),
  },
  {
    id: 'MS023',
    customerName: 'Wendy Young',
    customerSource: 'Social Media',
    status: 'Pending',
    orderCost: '$150.00',
    createdAt: new Date('2024-10-23'),
  },
  {
    id: 'MS024',
    customerName: 'Xander Zane',
    customerSource: 'Affiliate Link',
    status: 'Closed',
    orderCost: '$95.25',
    createdAt: new Date('2024-10-24'),
  },
  {
    id: 'MS025',
    customerName: 'Yara Allen',
    customerSource: 'Website',
    status: 'Active',
    orderCost: '$280.00',
    createdAt: new Date('2024-10-25'),
  },
  {
    id: 'MS026',
    customerName: 'Zoe Bell',
    customerSource: 'Mobile App',
    status: 'Pending',
    orderCost: '$190.50',
    createdAt: new Date('2024-10-26'),
  },
  {
    id: 'MS027',
    customerName: 'Aaron Cook',
    customerSource: 'Email Campaign',
    status: 'Closed',
    orderCost: '$220.00',
    createdAt: new Date('2024-10-27'),
  },
  {
    id: 'MS028',
    customerName: 'Bella Drew',
    customerSource: 'Referral',
    status: 'Active',
    orderCost: '$130.00',
    createdAt: new Date('2024-10-28'),
  },
  {
    id: 'MS029',
    customerName: 'Cody Frank',
    customerSource: 'Social Media',
    status: 'Pending',
    orderCost: '$250.00',
    createdAt: new Date('2024-10-29'),
  },
  {
    id: 'MS030',
    customerName: 'Daisy Gray',
    customerSource: 'Affiliate Link',
    status: 'Closed',
    orderCost: '$140.00',
    createdAt: new Date('2024-10-30'),
  },
];
